When run again ADW(19c) instances few querries with casewhen were failing with below error: ORA-00907: missing right parenthesis
select "W_WAREHOUSE_NAME", "I_ITEM_ID", "inv_before", "inv_after"
from ( select "W_WAREHOUSE_NAME", "I_ITEM_ID", "inv_before", "inv_after"
from ( select "W_WAREHOUSE_NAME", "I_ITEM_ID", SUM(CASE WHEN ("D_DATE" < TRUNC(TIMESTAMP '2000-03-11 00:00:00.000000')) THEN "INV_QUANTITY_ON_HAND" ELSE 0E-18 END) AS "inv_before", SUM(CASE WHEN ("D_DATE" >= TRUNC(TIMESTAMP '2000-03-11 00:00:00.000000')) THEN "INV_QUANTITY_ON_HAND" ELSE 0E-18 END) AS "inv_after"
from "TPCDS"."INVENTORY"  join "TPCDS"."WAREHOUSE"  on ("INV_WAREHOUSE_SK" = "W_WAREHOUSE_SK") join "TPCDS"."ITEM"  on ("INV_ITEM_SK" = "I_ITEM_SK") join "TPCDS"."DATE_DIM"  on ("INV_DATE_SK" = "D_DATE_SK")
where ((("I_CURRENT_PRICE" IS NOT NULL AND ("I_CURRENT_PRICE" >= ?)) AND ("I_CURRENT_PRICE" <= ?)) AND (("D_DATE" IS NOT NULL AND ("D_DATE" >= ?)) AND ("D_DATE" <= ?)))
group by "W_WAREHOUSE_NAME", "I_ITEM_ID" )
where (CASE WHEN ("inv_before" > ?) THEN (("inv_after" / "inv_before") >= ?)  END AND CASE WHEN ("inv_before" > ?) THEN (("inv_after" / "inv_before") <= ?)  END)
order by "W_WAREHOUSE_NAME" ASC NULLS FIRST, "I_ITEM_ID" ASC NULLS FIRST )
where rownum <= 100 on DataSourceKey(jdbc:oracle:thin:@karthik_low,tpcds) on DataSourceKey(jdbc:oracle:thin:@karthik_low,tpcds)
java.sql.SQLSyntaxErrorException: ORA-00907: missing right parenthesis

at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)

Signed-off-by: nrajhebbar <nagaraj.hebbar@oracle.com>